### ISSUE TITLE
Simulator non-obfuscated ?

### ISSUE THREAD

**Issue by DLwarez** [Eistee82/ta_simv2#1]
Hello

First of all i'd like to say you guys did a spleded job on the simulator.
It works near to perfect :+1: 

Since userscript.org went down GreasyFork.org kinda overtook it's place and since your fine script wasen't on there i took the liberty of sharing it.
I hope you don't mind.
Anyway... recently they changed the rules and it's no longer allowed to host obfuscated code so i whas wondering if you could share the non-obfuscated code.
And if you have no prob with it... could i share it again or if you'd like i could just delete my entry and you could share it your selves like you did before on the userscripts.org etc.

Greets,
DLwarez

**Comment by Eistee82** [comment]
Sorry we don't release an non-obfuscated version. If I do it gets integrated to Scriptpacks and there will be many old outdated versions. 2nd is there is much work in this script we did. The whole code is new. We also use a diffrent method to do the simulations in it and are using the EA API a difrent way than other simulators do. We fixed many ingame API functions to do right calculations wich also no other simulator does. So there are many reasons for us to not share the code.

**Comment by DLwarez** [comment]
Okey That's no problem.
I understand. You keep improving it. Niceee.
Tnx for your reply. Can't blame a guy for tryiing.
It still works great. Maybe you can build a improved version of the Mealstrom Tools with a basescanner that is much faster then the current versions.
That would improve the gameplay even more.
Ahh well... think about it
Would be nice to see some more work from you guys
This new EA API approach can be used to improve multiple tools for the CCTA game
